### ISSUE TITLE
Document Connected Components

### ISSUE THREAD

**Issue by buddha314** [pnnl/chgl#73]
This issue indicates CHGL supports finding connected components:  #11 but the [documentation](https://pnnl.github.io/chgl/search.html?q=component&check_keywords=yes&area=default) does not seem to show how to use this functionality. An example would be much appreciated.  Here is one pattern from [Grakn](https://dev.grakn.ai/docs/query/compute-query#compute-clusters-using-connected-component)

**Comment by jesunsahariar** [comment]
@buddha314 Thank you for reaching out to us and for your suggestion. While we are working on documenting the use of connected components, I thought it might be helpful to point out a set of steps that can be used for computing connected components. First, there are different ways to create a hypergraph. A toy example for creating a random graph is given [here](https://github.com/pnnl/chgl/blob/master/test/AdjListHyperGraph/graph-creation.chpl). We can also process input hypergraphs in csv format. An example can be found [here](https://github.com/pnnl/chgl/blob/master/example/activeDNS.chpl) ( and in general ActiveDNS is a good example of how to use different algorithms available in CHGL). Next once we create the hypergraph, we can compute the [vertex components](https://github.com/pnnl/chgl/blob/master/example/activeDNS.chpl#L164) or [edge components](https://github.com/pnnl/chgl/blob/master/example/activeDNS.chpl#L171) as shown in the activeDNS example (here we can see the use of the API for computing connected components). But in general, [the connected component algorithms](https://github.com/pnnl/chgl/blob/master/src/Metrics.chpl#L305) [are](https://github.com/pnnl/chgl/blob/master/src/Metrics.chpl#L315) available [here](https://github.com/pnnl/chgl/blob/master/src/Metrics.chpl). Please note: in the API s=1,2,3 etc. specifies how much overlap would be considered as the glueing factor (ie. for example for two hyperedges, specifying s=2 means we would only consider these edges as connected if they have at least 2 vertices in common and so on). I hope this will be helpful. If you have any questions, please feel free to reach out to us :-) . Thanks!
